
sensor:

##  sw01  ######################################################################

  - platform: snmp
    name: sw01_uptime
    host: !secret sw01_ip
    community: !secret snmp_ro
    baseoid: 1.3.6.1.2.1.1.3.0
    scan_interval: 2
    value_template: >
      {% set timetick = value  |int(0) %}
      {% set seconds = (timetick / 100) | round(0) | int(0) %}
      {% set days = (seconds / 60 / 60 / 24) | int(0)  %}
      {% set hours = ((seconds / 60 / 60) - (days * 24)) | int(0)  %}
      {% set minutes = ((seconds / 60 ) - ( hours * 60) - ( days * (24 * 60))) | int(0) %}

      {% if days  > 0 %}
        {{ days }} days,
      {% else %}
        {{ days }} day,
      {% endif %}
      {% if hours  > 0 %}
        {{ hours }} h
      {% else %}
        {{ 00 }} h
      {% endif %}
      {% if minutes  > 0 %}
        {% if minutes < 10 %}
          0{{ minutes }} m
        {% else %}
          {{ minutes }} m
        {% endif %}
      {% else %}
        {{ 00 }} m
      {% endif %}

  - platform: snmp
    name: sw01_ios_version
    host: !secret sw01_ip
    community: !secret snmp_ro
    baseoid: .1.3.6.1.2.1.1.1.0
    scan_interval: 10000

  - platform: snmp
    name: sw01_ios_bin
    host: !secret sw01_ip
    community: !secret snmp_ro
    baseoid: .1.3.6.1.2.1.16.19.6.0
    scan_interval: 10000

  - platform: snmp
    name: sw01_s2h_uplink_bytes_in
    host: !secret sw01_ip
    community: !secret snmp_ro
    baseoid: .1.3.6.1.2.1.2.2.1.10.10102
    scan_interval: 2

  - platform: snmp
    name: sw01_s2h_uplink_bytes_out
    host: !secret sw01_ip
    community: !secret snmp_ro
    baseoid: .1.3.6.1.2.1.2.2.1.16.10102
    scan_interval: 2

  ## cpu load monitors

  - platform: snmp
    name: sw01_cpu_load_1_min
    host: !secret sw01_ip
    community: !secret snmp_ro
    baseoid: .1.3.6.1.4.1.9.2.1.57.0
    scan_interval: 2

  - platform: snmp
    name: sw01_cpu_load_5_min
    host: !secret sw01_ip
    community: !secret snmp_ro
    baseoid: 1.3.6.1.4.1.9.2.1.58.0
    scan_interval: 2

  - platform: snmp
    name: sw01_cpu_load_5_sec
    host: !secret sw01_ip
    community: !secret snmp_ro
    baseoid: .1.3.6.1.4.1.9.2.1.56.0
    scan_interval: 2

    ## Indicates the number of bytes from the memory pool that are currently in use by applications on the managed device.
  - platform: snmp
    name: sw01_memory_util_bytes_used
    host: !secret sw01_ip
    community: !secret snmp_ro
    baseoid: .1.3.6.1.4.1.9.9.48.1.1.1.5.1
    scan_interval: 2

    ## Indicates the number of bytes from the memory pool that are currently unused on the managed device.
  - platform: snmp
    name: sw01_memory_util_bytes_unused
    host: !secret sw01_ip
    community: !secret snmp_ro
    baseoid: .1.3.6.1.4.1.9.9.48.1.1.1.6.1
    scan_interval: 2

  ## termplate sensors ########################################################

  - platform: template
    sensors:

      total_devices_sw01:
        friendly_name: 'Total Devices sw01'
        value_template: >
          {{ states.device_tracker
              | selectattr('attributes.scanner', 'eq', 'CiscoDeviceScanner')
              | list | count }}





###############################################################################

recorder:
  exclude:
    entities:
      # - binary_sensor.iss
      # - binary_sensor.fr24_feeder_link_connected
      - sensor.sw01_ios_version
      - sensor.sw01_memory_util_bytes_unused
      # - sensor.
      # - sensor.
      # - sensor.
      # - sensor.
      # - sensor.
      # - sensor.
      # - input_number.uplink_traffic_delta_ap02_in
      # - input_number.uplink_traffic_delta_ap02_out
      # - input_number.
      # - input_number.
    entity_globs:
      - sensor.sw01_ios_*
      - sensor.sw02_ios_*
      - sensor.sw03_ios_*
    #   - sensor.cisco_wlc_*_location
    #   - sensor.cisco_wlc_*_uptime
    #   - switch.cisco_wlc_*_led_state
    #   - sensor.sw*_ap*_uplink_bytes_*
    #   - input_number.uplink_traffic_delta_ap*

  # include:
  #   entities: sensor.flightairmap_count_all_tracked_aircraft




