#- platform: caldav
#  username: !secret nextcloud_user
#  password: !secret nextcloud_pass
#  url: !secret nextcloud_caldav_url

- platform: caldav
  username: !secret icloud3_user
  password: !secret icloud_hassio_caldev_apppwd
  url: !secret icloud_hassio_caldev_url
  calendars:
    - "Family"

#- platform: ics_calendar
#  calendars:
#    - name: "Astronomy Calendar"
#      url: "https://cantonbecker.com/astronomy-calendar/astrocal.ics"
#      include_all_day: true
#      download_interval: 21600

#- platform: ics_calendar
#  calendars:
#    - name: "Work Calendar"
#      url: !secret work_calendar_url
#      include_all_day: true
#      #download_interval: 21600
