## sensor to pull all local earthquakes ##############################
- platform: usgs_earthquakes_feed
  feed_type: "past_day_all_earthquakes"
  #feed_type: "past_month_all_earthquakes"
  radius: 600
  #minimum_magnitude: 0.0
  #latitude: 35.899722
  #longitude: -120.432778

  ## test sensor for only significant global quakes ####################
- platform: usgs_earthquakes_feed
  feed_type: "past_hour_significant_earthquakes"
  radius: 1500
