## battery binary sensors

## battery low alerts ##############################################################
- platform: template
  sensors:
    gmhqdc_multisensor_battery_low:
      value_template: '{{ states("sensor.multisensor_6_battery_level")|float < 35 }}'
      friendly_name: "GMHQ-DC Multisensor battery is low"

##