# Get indoor temperature and humidity trends.
- platform: trend
  sensors:
    ecobee_indoor_temperature_rising:
      entity_id: sensor.ecobee_temperature
      sample_duration: 7200
      max_samples: 120
      min_gradient: 0.00002755
      device_class: heat

    ecobee_indoor_temperature_falling:
      entity_id: sensor.ecobee_temperature
      sample_duration: 7200
      max_samples: 120
      min_gradient: -0.00002755
      device_class: cold

    ecobee_indoor_humidity_wetting:
      entity_id: sensor.ecobee_humidity
      sample_duration: 7200
      max_samples: 120
      min_gradient: 0.0008
      device_class: moisture

    ecobee_indoor_humidity_drying:
      entity_id: sensor.ecobee_humidity
      sample_duration: 7200
      max_samples: 120
      min_gradient: -0.0008
      device_class: moisture

# Get indoor temperature and humidity trends.
- platform: trend
  sensors:
    ecobee_outdoor_temperature_rising:
      entity_id: sensor.ecobee_temperature
      sample_duration: 7200
      max_samples: 120
      min_gradient: 0.00002755
      device_class: heat

    ecobee_outdoor_temperature_falling:
      entity_id: sensor.ecobee_temperature
      sample_duration: 7200
      max_samples: 120
      min_gradient: -0.00002755
      device_class: cold

    ecobee_outdoor_humidity_wetting:
      entity_id: sensor.ecobee_humidity
      sample_duration: 7200
      max_samples: 120
      min_gradient: 0.0008
      device_class: moisture

    ecobee_outdoor_humidity_drying:
      entity_id: sensor.ecobee_humidity
      sample_duration: 7200
      max_samples: 120
      min_gradient: -0.0008
      device_class: moisture