
- platform: template
  sensors:
    shop_motion:
      friendly_name: "Shop Motion"
      value_template: "{{ is_state('sensor.elkm1_shop_motion', 'Violated') }}"
      device_class: motion
      attribute_templates:
        actual: "{{ states('sensor.shop_motion') }}"

- platform: template
  sensors:
    shop_front_door:
      friendly_name: "Shop Front Door"
      value_template: "{{ is_state('sensor.shop_front_door', 'Violated') }}"
      device_class: door
      attribute_templates:
        actual: "{{ states('sensor.shop_front_door') }}"

- platform: template
  sensors:
    art_hut_motion:
      friendly_name: "Art Hut Motion"
      value_template: "{{ is_state('sensor.art_hut_motion', 'Violated') }}"
      device_class: motion
      attribute_templates:
        actual: "{{ states('sensor.art_hut_motion') }}"

- platform: template
  sensors:
    nws_alerts_are_active:
      friendly_name: NWS Alerts Are Active
      #entity_id: sensor.nws_alerts
      value_template: >
        {{ states('sensor.nws_alerts') | int(0) > 0 }}
      icon_template: >-
        {% if states('sensor.nws_alerts') | int(0) > 0 %}
          mdi:weather-lightning
        {% else %}
          mdi:weather-sunny
        {% endif %}
