# ADS-B System / Flightradar 24 / dump1090

homeassistant:
  customize:
    sensor.fr24_feeder:
      hidden: true
    sensor.fr24_feeder_aircraft_tracked:
      icon: mdi:airplane
    sensor.fr24_feeder_aircraft_uploaded:
      icon: mdi:airplane
    sensor.fr24_feeder_radar_code:
      icon: mdi:radar

binary_sensor:
  - platform: template
    sensors:
      fr24_feeder_receiver_connected:
        friendly_name: Receiver Connected
        value_template: '{{ is_state_attr("sensor.fr24_feeder", "rx_connected", "1") }}'
        device_class: connectivity

      fr24_feeder_link_connected:
        friendly_name: Link Connected
        value_template: '{{ is_state_attr("sensor.fr24_feeder", "feed_status", "connected") }}'
        device_class: connectivity

      adsb_lol_feeder_link_connected:
        friendly_name: Link Connected
        value_template: '{{ state_attr("sensor.adsb_lol_daily_stats", "beast_connected_seconds") | float(0) > 0 }}'
        device_class: connectivity

      adsb_fi_feeder_link_connected:
        friendly_name: Link Connected
        value_template: '{{ state_attr("sensor.adsb_fi_daily_stats", "beast_connected_seconds") | float(0) > 0 }}'
        device_class: connectivity

      # not working
      adsb_flyitaly_feeder_link_connected:
        friendly_name: Link Connected
        value_template: '{{ is_state_attr("sensor.adsb_flyitaly_stats", "mlat", "true") }}'
        device_class: connectivity

      radarplane_feeder_link_connected:
        friendly_name: Link Connected
        value_template: '{{ state_attr("sensor.radarplane_stats", "connection_time") | float(0) > 0 }}'
        device_class: connectivity

      airplanes_live_feeder_link_connected:
        friendly_name: Link Connected
        value_template: '{{ is_state_attr("sensor.airplanes_live_connected", "beast_connected", "Success!") }}'
        device_class: connectivity

      adsb_exchange_feeder_link_connected:
        friendly_name: Link Connected
        value_template: '{{ is_state_attr("sensor.adsb_exchange_status", "beast_status", "Feed Ok ADS-B Status") }}'
        device_class: connectivity

      piaware_feeder_link_connected:
        friendly_name: Link Connected
        value_template: '{{ is_state_attr("sensor.piaware_conn_status", "piaware_status", "green") }}'
        device_class: connectivity

      piaware_radio_link_connected:
        friendly_name: Link Connected
        value_template: '{{ is_state_attr("sensor.piaware_conn_status", "radio_status", "green") }}'
        device_class: connectivity

      piaware_adept_feeder_link_connected:
        friendly_name: Link Connected
        value_template: '{{ is_state_attr("sensor.piaware_conn_status", "adept_status", "green") }}'
        device_class: connectivity

      piaware_mlat_feeder_link_connected:
        friendly_name: Link Connected
        value_template: '{{ is_state_attr("sensor.piaware_conn_status", "mlat_status", "green") }}'
        device_class: connectivity



sensor:
  - platform: rest
    name: FR24 Feeder
    resource: !secret dump1090_api_url
    # resource: http://10.x.x.x:8754/monitor.json
    value_template: '{{ value_json.feed_alias }}'
    method: GET
    scan_interval: 60
    json_attributes:
      - rx_connected
      - feed_status
      - d11_map_size
      - feed_num_ac_tracked
      - build_version
      - feed_alias

  - platform: template
    sensors:
      fr24_feeder_radar_code:
        friendly_name: Radar Code
        value_template: '{{ states.sensor.fr24_feeder.attributes["feed_alias"] }}'
      fr24_feeder_aircraft_tracked:
        friendly_name: Aircraft Tracking
        value_template: '{{ states.sensor.fr24_feeder.attributes["d11_map_size"] | round(0) }}'
        unit_of_measurement: 'aircraft'
      fr24_feeder_aircraft_uploaded:
        friendly_name: Aircraft with Coordinates
        value_template: '{{ states.sensor.fr24_feeder.attributes["feed_num_ac_tracked"] | round(0) }}'
        unit_of_measurement: 'aircraft'
      fr24_feeder_version:
        friendly_name: Version
        value_template: '{{ states.sensor.fr24_feeder.attributes["build_version"] }}'

  - platform: rest
    name: FR24 Aircraft
    #resource: http://10.x.x.x:8080/data/aircraft.json
    resource: !secret flightaware_api_url
    value_template: "{{ value_json.messages }}"
    method: GET
    scan_interval: 15
    json_attributes:
      - now
      - aircraft

  - platform: template
    sensors:
      adsb_lol_beast_positions_per_second:
        friendly_name: ADSB.lol - Positions Uploaded per Second
        value_template: '{{ states.sensor.adsb_lol_daily_stats.attributes["beast_positions_per_second"] }}'
      adsb_lol_beast_positions_kbs:
        friendly_name: ADSB.lol - Uplink Throughput
        value_template: '{{ states.sensor.adsb_lol_daily_stats.attributes["kbps"] | round(2) }}'
        unit_of_measurement: 'kbps'



multiscrape:
## scrape adsb.lol stats ###########################################################

  - name: adsb.lol stats
    #resource: !secret openmeteo_api
    resource: https://api.adsb.lol/0/me
    scan_interval: 60
    sensor:

      - unique_id: adsb_lol_daily_stats
        name: ADSB.lol - Daily Stats
        value_template: Connected
        icon: mdi:plane
        attributes:
          - name: global_aircraft
            value_template: '{{ value_json.global.aircraft }}'
          - name: global_beast
            value_template: '{{ value_json.global.beast }}'
          - name: global_mlat
            value_template: '{{ value_json.global.mlat }}'
          - name: beast_connected_seconds
            value_template: '{{ value_json.clients.beast[0].connected_seconds }}'
          - name: beast_kbps
            value_template: '{{ value_json.clients.beast[0].kbps }}'
          - name: beast_ms
            value_template: '{{ value_json.clients.beast[0].ms }}'
          - name: beast_messages_per_second
            value_template: '{{ value_json.clients.beast[0].messages_per_second }}'
          - name: beast_positions
            value_template: '{{ value_json.clients.beast[0].positions }}'
          - name: beast_positions_per_second
            value_template: '{{ value_json.clients.beast[0].positions_per_second }}'
          - name: mlat_peer_count
            value_template: '{{ value_json.clients.mlat[0].peer_count }}'
          - name: mlat_outlier_percent
            value_template: '{{ value_json.clients.mlat[0].outlier_percent }}'
          - name: mlat_bad_sync_timeout
            value_template: '{{ value_json.clients.mlat[0].bad_sync_timeout }}'

## scrape adsb.fi stats ###########################################################

  - name: adsb.fi stats
    #resource: !secret openmeteo_api
    resource: https://api.adsb.fi/v1/myip
    scan_interval: 60
    sensor:

      - unique_id: adsb_fi_daily_stats
        name: ADSB.fi - Daily Stats
        value_template: Connected
        icon: mdi:plane
        attributes:
          - name: beast_connected_seconds
            value_template: '{{ value_json.beast[0].connTime }}'
          - name: beast_bandwidth
            value_template: '{{ value_json.beast[0].bandwidth }}'
          - name: beast_recentRtt
            value_template: '{{ value_json.beast[0].recentRtt }}'
          - name: beast_messages_per_second
            value_template: '{{ value_json.beast[0].messageRate }}'
          - name: beast_positions
            value_template: '{{ value_json.beast[0].positions }}'
          - name: beast_positions_per_second
            value_template: '{{ value_json.beast[0].positionRate }}'
          - name: mlat_messages_per_second
            value_template: '{{ value_json.mlat[0].messageRate }}'
          - name: mlat_peer_count
            value_template: '{{ value_json.mlat[0].peerCount }}'
          - name: mlat_outlier_percent
            value_template: '{{ value_json.mlat[0].outlierPercent }}'
          - name: mlat_bad_sync_timeout
            value_template: '{{ value_json.mlat[0].badSyncTimeout }}'

## scrape FlyItaly adsb stats ###########################################################

  - name: FlyItaly adsb stats
    #resource: !secret openmeteo_api
    resource: https://my.flyitalyadsb.com/am_i_feeding
    scan_interval: 60
    sensor:

      - unique_id: adsb_flyitaly_stats
        name: FlyItaly ADSB - Stats
        value_template: Connected
        icon: mdi:plane
        attributes:
          - name: beast
            value_template: '{{ value_json.feeding.beast }}'
          - name: mlat
            value_template: '{{ value_json.feeding.mlat }}'

## scrape RadarPlane stats ###########################################################

  - name: RadarPlane Stats
    resource: https://radarplane.com/feed
    scan_interval: 60
    #log_response: true
    sensor:

      - unique_id: radarplane_stats
        name: RadarPlane Stats
        value_template: Connected
        icon: mdi:plane
        attributes:
          - name: connection_time
            select: 'body > div.flex-grow > div > div > div:nth-child(4) > div.mt-5.overflow-auto > table > tbody > tr > td:nth-child(4)'
          - name: msg_sec
            select: 'body > div.flex-grow > div > div > div:nth-child(4) > div.mt-5.overflow-auto > table > tbody > tr > td:nth-child(5)'
          - name: pos_sec
            select: 'body > div.flex-grow > div > div > div:nth-child(4) > div.mt-5.overflow-auto > table > tbody > tr > td:nth-child(6)'
          - name: kbs
            select: 'body > div.flex-grow > div > div > div:nth-child(4) > div.mt-5.overflow-auto > table > tbody > tr > td:nth-child(3)'


## scrape Airplanes.live stats ###########################################################

  - name: Airplanes.live connected
    resource: https://airplanes.live/myfeed/
    scan_interval: 60
    #log_response: true
    sensor:

      - unique_id: airplanes_live_connected
        name: Airplanes.live - Uplink Status
        value_template: Connected
        icon: mdi:plane
        attributes:
          - name: beast_connected
            select: '#beast-detect > div > div > span'
          - name: mlat_connected
            select: '#mlat-detect > div > div > span'


## scrape TheAirTraffic stats ###########################################################

  - name: ADSB Exchange Status
    resource: https://www.adsbexchange.com/myip/
    scan_interval: 60
    #log_response: true
    sensor:

      - unique_id: adsb_exchange_status
        name: ADSB Exchange - Uplink Status
        value_template: Connected
        icon: mdi:plane
        attributes:
          - name: beast_status
            select: '#feeder-status > div > div.col.text-center.m-3.p-2 > div > div > div:nth-child(4) > div:nth-child(1) > small'
          - name: mlat_status
            select: '#feeder-status > div > div.col.text-center.m-3.p-2 > div > div > div:nth-child(4) > div:nth-child(2) > small'
          # - name: beast_kbs
          #   select: '#feeder-status > div > div.col.text-center.m-3.p-2 > div > div > div:nth-child(4) > div:nth-child(2) > input'

## scrape FlightAirMap stats ###########################################################

  - name: FlightAirMap Stats
    resource: !secret fam_stats_url
    scan_interval: 60
    #log_response: true
    sensor:

      - unique_id: flightairmap_stats
        name: FlightAirMap Stats
        value_template: Connected
        icon: mdi:plane
        attributes:
          - name: arrivals_seen
            select: 'body > section > div > p > span:nth-child(2) > span'
          - name: aircraft_type
            select: 'body > section > div > p > span:nth-child(4) > span'
          - name: owners
            select: 'body > section > div > p > span:nth-child(3) > span'
          - name: military_flights ## not accurate for some reason, use the sql query
            select: 'body > section > div > p > span:nth-child(6) > span'
          - name: airlines
            select: 'body > section > div > p > span:nth-child(5) > span'
          - name: flights
            select: 'body > section > div > p > span:nth-child(1) > span'


  - name: FlightAware PiAware Status
    resource: !secret piaware_status_url
    scan_interval: 30
    #log_response: true
    sensor:
      - unique_id: piaware_conn_status
        name: FlightAware PiAware Status
        value_template: Connected
        icon: mdi:plane
        attributes:
          - name: adept_status
            value_template: '{{ value_json.adept.status }}'
          - name: cpu_load_percent
            value_template: '{{ value_json.cpu_load_percent }}'
          - name: cpu_temp_celcius
            value_template: '{{ value_json.cpu_temp_celcius }}'
          - name: mlat_status
            value_template: '{{ value_json.mlat.status }}'
          - name: piaware_status
            value_template: '{{ value_json.piaware.status }}'
          - name: piaware_version
            value_template: '{{ value_json.piaware_version }}'
          - name: radio_status
            value_template: '{{ value_json.radio.status }}'
          - name: system_uptime
            value_template: '{{ value_json.system_uptime }}'




##############################################################################################
#####################  need work #############################################################

## scrape TheAirTraffic stats ###########################################################
  - name: TheAirTraffic connected
    resource: https://theairtraffic.com/feed/myip/
    scan_interval: 60
    #log_response: true
    sensor:

      - unique_id: the_air_traffic_status
        name: TheAirTraffic - Uplink Status
        value_template: Connected
        icon: mdi:plane
        attributes:
          - name: beast_status
            select: '#beast_status'
          - name: mlat_status
            select: '#mlat_status'
          - name: beast_kbs
            select: '#details > span:nth-child(3)'


    # not working
  - name: Airplanes.live Stats
    resource: https://airplanes.live/myfeed/
    scan_interval: 60
    #log_response: true
    sensor:

      - unique_id: airplanes_live_daily_stats
        name: Airplanes.live - Daily Stats
        value_template: Connected
        icon: mdi:tank
        attributes:
          - name: beast
            #select: 'pre#feeder-json'
            value_template: '{{ value_json.mlat_clients[0].peer_count }}'
          - name: messageRate
            select: '#feeder-json > #text'
            value_template: '{{ value_json.mlat_clients[0].outlier_percent }}'






recorder:
  exclude:
    entities:
      - binary_sensor.fr24_feeder_receiver_connected
      - binary_sensor.fr24_feeder_link_connected
      - sensor.fr24_feeder_radar_code
      - sensor.fr24_feeder_aircraft_tracked
      - sensor.fr24_feeder_version
      - sensor.adsb_lol_daily_stats
      - sensor.adsb_fi_daily_stats
      - sensor.adsb_flyitaly_stats
      - sensor.piaware_conn_status
      - sensor.fr24_feeder
  #include:


